export const CHECK_AUTHORIZATION_REQUEST = 'App/CHECK_AUTHORIZATION_REQUEST';
export const CHECK_AUTHORIZATION_SUCCESS = 'App/CHECK_AUTHORIZATION_SUCCESS';
export const CHECK_AUTHORIZATION_FAILURE = 'App/CHECK_AUTHORIZATION_FAILURE';

export const SIGN_IN_REQUEST = 'App/SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'App/SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'App/SIGN_IN_FAILURE';
