export const CHECK_AUTHORIZATION_REQUEST = 'App/CHECK_AUTHORIZATION_REQUEST';
export const CHECK_AUTHORIZATION_SUCCESS = 'App/CHECK_AUTHORIZATION_SUCCESS';
export const CHECK_AUTHORIZATION_FAILURE = 'App/CHECK_AUTHORIZATION_FAILURE';

export const SIGN_IN_REQUEST = 'App/SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'App/SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'App/SIGN_IN_FAILURE';

export const SIGN_UP_REQUEST = 'App/SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'App/SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'App/SIGN_UP_FAILURE';

export const UPDATE_USER_REQUEST = 'App/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'App/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'App/UPDATE_USER_FAILURE';

export const UPDATE_USER_PASSWORD_SUCCESS = 'App/UPDATE_USER_PASSWORD_SUCCESS';

export const GET_SUBUSERS_REQUEST = 'App/GET_SUBUSERS_REQUEST';
export const GET_SUBUSERS_SUCCESS = 'App/GET_SUBUSERS_SUCCESS';
export const GET_SUBUSERS_FAILURE = 'App/GET_SUBUSERS_FAILURE';

export const CREATE_SUBUSER_REQUEST = 'App/CREATE_SUBUSER_REQUEST';
export const CREATE_SUBUSER_SUCCESS = 'App/CREATE_SUBUSER_SUCCESS';
export const CREATE_SUBUSER_FAILURE = 'App/CREATE_SUBUSER_FAILURE';

export const UPDATE_SUBUSER_REQUEST = 'App/UPDATE_SUBUSER_REQUEST';
export const UPDATE_SUBUSER_SUCCESS = 'App/UPDATE_SUBUSER_SUCCESS';
export const UPDATE_SUBUSER_FAILURE = 'App/UPDATE_SUBUSER_FAILURE';

export const DELETE_SUBUSER_REQUEST = 'App/DELETE_SUBUSER_REQUEST';
export const DELETE_SUBUSER_SUCCESS = 'App/DELETE_SUBUSER_SUCCESS';
export const DELETE_SUBUSER_FAILURE = 'App/DELETE_SUBUSER_FAILURE';

export const SIGN_OUT = 'App/SIGN_OUT';