export const CHECK_AUTHORIZATION_REQUEST = 'App/CHECK_AUTHORIZATION_REQUEST';
export const CHECK_AUTHORIZATION_SUCCESS = 'App/CHECK_AUTHORIZATION_SUCCESS';
export const CHECK_AUTHORIZATION_FAILURE = 'App/CHECK_AUTHORIZATION_FAILURE';

export const SIGN_IN_REQUEST = 'App/SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'App/SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'App/SIGN_IN_FAILURE';

export const CREATE_USER_REQUEST = 'App/CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'App/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'App/CREATE_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'App/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'App/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'App/UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'App/DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'App/DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'App/DELETE_USER_FAILURE';

export const UPDATE_USER_PASSWORD_SUCCESS = 'App/UPDATE_USER_PASSWORD_SUCCESS';

export const GET_SUBUSERS_REQUEST = 'App/GET_SUBUSERS_REQUEST';
export const GET_SUBUSERS_SUCCESS = 'App/GET_SUBUSERS_SUCCESS';
export const GET_SUBUSERS_FAILURE = 'App/GET_SUBUSERS_FAILURE';

export const CREATE_UPDATE_USER_RESET = 'App/CREATE_UPDATE_USER_RESET';

export const SIGN_OUT = 'App/SIGN_OUT';